server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = / {
        return 302 /entrega/;
    }

    location /entrega/ {
        alias /usr/share/nginx/html/entrega/;
        index index.html;
        try_files $uri $uri/ /entrega/index.html;
        add_header Cache-Control "no-cache";
    }

    location /entrega/bombas {
        alias /usr/share/nginx/html/entrega/bombas.html;
        add_header Cache-Control "no-cache";
    }
}
